/* The following code was generated by JFlex 1.5.1 */

package org.jetbrains.yesod.julius.parser;

/**
 * @author Leyla H
 */

import java.util.*;
import com.intellij.lexer.*;
import com.intellij.psi.*;
import org.jetbrains.haskell.parser.token.*;
import com.intellij.psi.tree.IElementType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.1
 * from the specification file <tt>/Users/atsky/work/haskell-idea-plugin/plugin/src/org/jetbrains/yesod/julius/parser/Julius.flex</tt>
 */
class _JuliusLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\2\1\45\1\46\1\45\22\0\1\1\1\0\1\47"+
    "\1\10\1\13\2\0\1\44\2\0\1\12\2\0\1\0\1\0\1\3"+
    "\12\0\1\34\4\0\1\7\1\5\33\0\1\43\1\0\1\11\1\14"+
    "\1\0\1\16\1\35\1\23\1\37\1\30\1\20\1\42\1\33\1\25"+
    "\1\0\1\36\1\31\1\0\1\22\1\26\1\41\1\0\1\17\1\27"+
    "\1\24\1\21\1\15\1\32\1\0\1\40\1\0\1\6\1\0\1\4"+
    "\7\0\1\45\u1fa2\0\1\45\1\45\udfd6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\4\1\1\5"+
    "\1\6\12\1\1\7\2\1\1\10\2\1\1\11\1\12"+
    "\1\13\1\0\1\14\1\15\1\16\13\0\1\17\1\20"+
    "\5\0\1\21\3\0\1\22\2\0\1\23\1\24\3\0"+
    "\1\25\1\26\3\0\1\27\20\0\1\30\2\0\1\31"+
    "\3\0\1\32\1\33\10\0\1\34\1\0\1\35\3\0"+
    "\1\36\1\37\3\0\1\40\3\0\1\41\1\0\1\42"+
    "\1\0\1\43\2\0\1\44\2\0\1\45\1\0\1\46"+
    "\1\47\1\0\1\50\1\0\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\50\0\170\0\50\0\240\0\310"+
    "\0\360\0\u0118\0\50\0\50\0\u0140\0\u0168\0\u0190\0\u01b8"+
    "\0\u01e0\0\u0208\0\u0230\0\u0258\0\u0280\0\u02a8\0\50\0\u02d0"+
    "\0\u02f8\0\50\0\u0320\0\u0348\0\50\0\50\0\50\0\u0370"+
    "\0\50\0\50\0\50\0\u0398\0\u03c0\0\u03e8\0\u0410\0\u0438"+
    "\0\u0460\0\u0488\0\u04b0\0\u04d8\0\u0500\0\u0528\0\50\0\u0550"+
    "\0\u0578\0\u05a0\0\u05c8\0\u05f0\0\u0618\0\50\0\u0640\0\u0320"+
    "\0\u0668\0\50\0\u0348\0\u0690\0\50\0\50\0\u06b8\0\u06e0"+
    "\0\u0708\0\50\0\50\0\u0730\0\u0758\0\u0780\0\50\0\u07a8"+
    "\0\u07d0\0\u07f8\0\u0820\0\u0848\0\u0870\0\u0898\0\u08c0\0\u08e8"+
    "\0\u0910\0\u0938\0\u0960\0\u0988\0\u09b0\0\u09d8\0\u0a00\0\50"+
    "\0\u0a28\0\u0a50\0\50\0\u0a78\0\u0aa0\0\u0ac8\0\50\0\50"+
    "\0\u0af0\0\u0b18\0\u0b40\0\u0b68\0\u0b90\0\u0bb8\0\u0be0\0\u0c08"+
    "\0\50\0\u0c30\0\50\0\u0c58\0\u0c80\0\u0ca8\0\50\0\50"+
    "\0\u0cd0\0\u0cf8\0\u0d20\0\50\0\u0d48\0\u0d70\0\u0d98\0\50"+
    "\0\u0dc0\0\50\0\u0de8\0\50\0\u0e10\0\u0e38\0\50\0\u0e60"+
    "\0\u0e88\0\50\0\u0eb0\0\50\0\50\0\u0ed8\0\50\0\u0f00"+
    "\0\50";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\2\2\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\2\1\16\1\17"+
    "\1\2\1\20\1\21\1\22\1\23\1\2\1\24\1\25"+
    "\1\2\1\26\1\2\1\27\1\30\1\2\1\31\3\2"+
    "\1\32\1\33\1\0\1\3\1\34\51\0\1\3\44\0"+
    "\1\3\4\0\1\35\6\0\1\36\43\0\1\37\1\40"+
    "\46\0\1\41\47\0\1\42\44\0\1\43\62\0\1\44"+
    "\61\0\1\45\40\0\1\46\3\0\1\47\1\50\51\0"+
    "\1\51\35\0\1\52\7\0\1\53\40\0\1\54\13\0"+
    "\1\55\4\0\1\56\27\0\1\57\1\0\1\60\57\0"+
    "\1\61\46\0\1\62\43\0\1\63\5\0\1\64\33\0"+
    "\1\65\56\0\1\66\1\0\1\67\17\0\43\70\1\71"+
    "\1\72\3\70\43\73\1\74\3\73\1\72\6\0\1\75"+
    "\60\0\1\76\54\0\1\77\45\0\1\100\47\0\1\101"+
    "\44\0\1\102\62\0\1\103\41\0\1\104\2\0\1\105"+
    "\42\0\1\106\65\0\1\107\26\0\1\110\5\0\1\111"+
    "\63\0\1\112\35\0\1\113\45\0\1\114\51\0\1\115"+
    "\44\0\1\116\50\0\1\117\52\0\1\120\37\0\1\121"+
    "\10\0\1\122\3\0\1\123\12\0\2\70\1\0\42\70"+
    "\2\0\1\70\2\73\1\0\42\73\2\0\1\73\21\0"+
    "\1\124\51\0\1\125\42\0\1\126\54\0\1\127\54\0"+
    "\1\130\43\0\1\131\51\0\1\132\50\0\1\133\50\0"+
    "\1\134\43\0\1\135\47\0\1\136\53\0\1\137\52\0"+
    "\1\140\45\0\1\141\34\0\1\142\47\0\1\143\61\0"+
    "\1\144\40\0\1\145\45\0\1\146\54\0\1\147\54\0"+
    "\1\150\51\0\1\151\41\0\1\152\54\0\1\153\43\0"+
    "\1\154\37\0\1\155\54\0\1\156\54\0\1\157\55\0"+
    "\1\160\32\0\1\161\52\0\1\162\65\0\1\163\27\0"+
    "\1\164\52\0\1\165\53\0\1\166\40\0\1\167\45\0"+
    "\1\170\51\0\1\171\60\0\1\172\45\0\1\173\46\0"+
    "\1\174\61\0\1\175\33\0\1\176\61\0\1\177\30\0"+
    "\1\200\51\0\1\201\50\0\1\202\53\0\1\203\41\0"+
    "\1\204\55\0\1\205\47\0\1\206\36\0\1\207\56\0"+
    "\1\210\41\0\1\211\27\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3880];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\1\1\1\11\4\1\2\11"+
    "\12\1\1\11\2\1\1\11\2\1\3\11\1\0\3\11"+
    "\13\0\1\11\1\1\5\0\1\11\3\0\1\11\2\0"+
    "\2\11\3\0\2\11\3\0\1\11\20\0\1\11\2\0"+
    "\1\11\3\0\2\11\10\0\1\11\1\0\1\11\3\0"+
    "\2\11\3\0\1\11\3\0\1\11\1\0\1\11\1\0"+
    "\1\11\2\0\1\11\2\0\1\11\1\0\2\11\1\0"+
    "\1\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char[] zzBuffer = new char[0];

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  _JuliusLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  _JuliusLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer.toString().toCharArray();
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { return TokenType.BAD_CHARACTER;
          }
        case 42: break;
        case 2: 
          { return TokenType.WHITE_SPACE;
          }
        case 43: break;
        case 3: 
          { return JuliusTokenTypes.NEWLINE;
          }
        case 44: break;
        case 4: 
          { return JuliusTokenTypes.CCURLY;
          }
        case 45: break;
        case 5: 
          { return JuliusTokenTypes.DOLLAR;
          }
        case 46: break;
        case 6: 
          { return JuliusTokenTypes.UNDERLINE;
          }
        case 47: break;
        case 7: 
          { return JuliusTokenTypes.COLON;
          }
        case 48: break;
        case 8: 
          { return JuliusTokenTypes.BACKSLASH;
          }
        case 49: break;
        case 9: 
          { return JuliusTokenTypes.COMMENTS;
          }
        case 50: break;
        case 10: 
          { return JuliusTokenTypes.COMMENT_START;
          }
        case 51: break;
        case 11: 
          { return JuliusTokenTypes.AT;
          }
        case 52: break;
        case 12: 
          { return JuliusTokenTypes.SHARP;
          }
        case 53: break;
        case 13: 
          { return JuliusTokenTypes.HAT;
          }
        case 54: break;
        case 14: 
          { return JuliusTokenTypes.COMMENT_END;
          }
        case 55: break;
        case 15: 
          { return JuliusTokenTypes.IF;
          }
        case 56: break;
        case 16: 
          { return JuliusTokenTypes.IN;
          }
        case 57: break;
        case 17: 
          { return JuliusTokenTypes.DO;
          }
        case 58: break;
        case 18: 
          { return JuliusTokenTypes.STRING;
          }
        case 59: break;
        case 19: 
          { return JuliusTokenTypes.ATWITHQ;
          }
        case 60: break;
        case 20: 
          { return JuliusTokenTypes.VAR;
          }
        case 61: break;
        case 21: 
          { return JuliusTokenTypes.FOR;
          }
        case 62: break;
        case 22: 
          { return JuliusTokenTypes.NEW;
          }
        case 63: break;
        case 23: 
          { return JuliusTokenTypes.TRY;
          }
        case 64: break;
        case 24: 
          { return JuliusTokenTypes.CASE;
          }
        case 65: break;
        case 25: 
          { return JuliusTokenTypes.THIS;
          }
        case 66: break;
        case 26: 
          { return JuliusTokenTypes.ELSE;
          }
        case 67: break;
        case 27: 
          { return JuliusTokenTypes.WITH;
          }
        case 68: break;
        case 28: 
          { return JuliusTokenTypes.CATCH;
          }
        case 69: break;
        case 29: 
          { return JuliusTokenTypes.THROW;
          }
        case 70: break;
        case 30: 
          { return JuliusTokenTypes.WHILE;
          }
        case 71: break;
        case 31: 
          { return JuliusTokenTypes.BREAK;
          }
        case 72: break;
        case 32: 
          { return JuliusTokenTypes.RETURN;
          }
        case 73: break;
        case 33: 
          { return JuliusTokenTypes.TYPEOF;
          }
        case 74: break;
        case 34: 
          { return JuliusTokenTypes.SWITCH;
          }
        case 75: break;
        case 35: 
          { return JuliusTokenTypes.DELETE;
          }
        case 76: break;
        case 36: 
          { return JuliusTokenTypes.FINALLY;
          }
        case 77: break;
        case 37: 
          { return JuliusTokenTypes.DEFAULT;
          }
        case 78: break;
        case 38: 
          { return JuliusTokenTypes.FUNCTION;
          }
        case 79: break;
        case 39: 
          { return JuliusTokenTypes.CONTINUE;
          }
        case 80: break;
        case 40: 
          { return JuliusTokenTypes.DEBUGGER;
          }
        case 81: break;
        case 41: 
          { return JuliusTokenTypes.INSTANCEOF;
          }
        case 82: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
