/* The following code was generated by JFlex 1.4.3 on 11.01.14 1:21 */

package org.jetbrains.haskell.parser;

import java.util.*;
import com.intellij.lexer.*;
import com.intellij.psi.*;
import org.jetbrains.haskell.parser.token.*;
import com.intellij.psi.tree.IElementType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11.01.14 1:21 from the specification file
 * <tt>C:/Users/Евгений/Dropbox/haskell-idea-plugin/plugin/src/org/jetbrains/haskell/parser/Haskell.flex</tt>
 */
class _HaskellLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int BLOCK_COMMENT = 2;
  public static final int YYINITIAL = 0;
  public static final int TEX = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\3\0\1\3\1\0\1\0\3\0\1\10\1\1\1\0\1\10\1\0"+
    "\22\0\1\10\1\0\1\6\1\55\1\0\2\0\1\7\1\27\1\30"+
    "\1\0\1\0\1\34\1\11\1\33\1\0\12\2\1\31\1\32\1\0"+
    "\1\35\1\37\2\0\32\4\1\25\1\12\1\26\1\0\1\5\1\0"+
    "\1\41\1\13\1\21\1\23\1\14\1\45\1\15\1\46\1\16\2\5"+
    "\1\44\1\47\1\17\1\22\1\51\1\5\1\52\1\42\1\43\1\50"+
    "\1\5\1\54\1\5\1\53\1\5\1\20\1\36\1\24\1\0\u2113\0"+
    "\1\40\155\0\1\56\uddff\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\6\2\2"+
    "\1\7\1\2\1\10\2\6\1\11\3\6\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\12\6\1\26\1\1\1\0\2\1\1\0"+
    "\1\27\3\0\1\30\1\0\1\6\1\31\1\32\1\6"+
    "\1\0\3\6\1\33\1\6\1\34\1\6\1\0\1\35"+
    "\16\6\1\0\1\36\1\1\1\0\1\27\2\37\1\0"+
    "\3\6\1\40\1\0\5\6\1\41\2\6\1\42\14\6"+
    "\2\0\1\43\2\6\1\0\1\6\1\44\1\6\1\45"+
    "\1\46\1\47\1\50\12\6\1\51\1\6\2\0\2\6"+
    "\1\0\1\6\1\52\1\53\4\6\1\54\4\6\1\55"+
    "\2\0\1\6\1\56\1\57\1\6\1\26\1\60\1\61"+
    "\1\62\1\6\1\63\1\6\1\64\2\0\4\6\2\0"+
    "\1\65\2\6\1\66\2\0\1\6\1\67\1\0\1\70"+
    "\1\6\1\0\1\71\1\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[194];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292\0\u02c1"+
    "\0\u02f0\0\u031f\0\u034e\0\215\0\215\0\215\0\215\0\215"+
    "\0\215\0\215\0\u037d\0\215\0\215\0\215\0\215\0\u03ac"+
    "\0\u03db\0\u040a\0\u0439\0\u0468\0\u0497\0\u04c6\0\u04f5\0\u0524"+
    "\0\u0553\0\215\0\u0582\0\u05b1\0\u05e0\0\u060f\0\u0178\0\215"+
    "\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa\0\u0729\0\u0758\0\u0149"+
    "\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0149\0\u0872\0\u0149"+
    "\0\u08a1\0\u08d0\0\u0149\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb"+
    "\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33"+
    "\0\u0b62\0\u0b91\0\215\0\u0bc0\0\u0bef\0\u0178\0\215\0\u066d"+
    "\0\u0c1e\0\u0c4d\0\u0c7c\0\u0cab\0\215\0\u0cda\0\u0d09\0\u0d38"+
    "\0\u0d67\0\u0d96\0\u0dc5\0\215\0\u0df4\0\u0e23\0\u0149\0\u0e52"+
    "\0\u0e81\0\u0eb0\0\u0edf\0\u0f0e\0\u0f3d\0\u0f6c\0\u0f9b\0\u0fca"+
    "\0\u0ff9\0\u1028\0\u1057\0\u1086\0\u10b5\0\u0149\0\u10e4\0\u1113"+
    "\0\u1142\0\u1171\0\u0149\0\u11a0\0\u0149\0\u0149\0\u0149\0\u0149"+
    "\0\u11cf\0\u11fe\0\u122d\0\u125c\0\u128b\0\u12ba\0\u12e9\0\u1318"+
    "\0\u1347\0\u1376\0\u0149\0\u13a5\0\u13d4\0\u1403\0\u1432\0\u1461"+
    "\0\u1490\0\u14bf\0\u0149\0\u0149\0\u14ee\0\u151d\0\u154c\0\u157b"+
    "\0\u0149\0\u15aa\0\u15d9\0\u1608\0\u1637\0\u0149\0\u1666\0\u1695"+
    "\0\u16c4\0\u0149\0\u0cda\0\u16f3\0\u0149\0\u0149\0\u0149\0\u0149"+
    "\0\u1722\0\u0149\0\u1751\0\u0149\0\u1780\0\u17af\0\u17de\0\u180d"+
    "\0\u183c\0\u186b\0\u189a\0\u18c9\0\u0149\0\u18f8\0\u1927\0\u0149"+
    "\0\u1956\0\u1985\0\u19b4\0\u0149\0\u19e3\0\215\0\u1a12\0\u1a41"+
    "\0\u0149\0\u1a70";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[194];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\4\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\10\1\16\1\10\1\17\1\10"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\4"+
    "\1\37\1\40\1\10\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\10\1\51\1\4\1\52\11\53"+
    "\1\54\45\53\12\55\1\56\44\55\67\0\1\5\50\0"+
    "\1\6\56\0\4\7\1\0\1\7\3\0\5\7\1\0"+
    "\3\7\15\0\14\7\4\0\4\10\1\0\1\10\3\0"+
    "\5\10\1\0\3\10\15\0\14\10\2\0\6\57\1\60"+
    "\3\57\1\61\44\57\7\62\1\0\2\62\1\63\44\62"+
    "\10\0\1\13\57\0\1\64\25\0\1\37\33\0\1\65"+
    "\44\0\4\10\1\0\1\10\3\0\5\10\1\0\3\10"+
    "\15\0\3\10\1\66\10\10\4\0\4\10\1\0\1\10"+
    "\3\0\4\10\1\67\1\0\3\10\15\0\4\10\1\70"+
    "\1\10\1\71\5\10\13\0\1\72\47\0\4\10\1\0"+
    "\1\10\3\0\5\10\1\0\1\10\1\73\1\10\15\0"+
    "\1\74\2\10\1\75\10\10\4\0\4\10\1\0\1\10"+
    "\3\0\5\10\1\0\3\10\15\0\4\10\1\76\3\10"+
    "\1\77\3\10\4\0\4\10\1\0\1\10\3\0\5\10"+
    "\1\0\1\10\1\100\1\10\15\0\1\101\13\10\35\0"+
    "\1\102\25\0\4\10\1\0\1\10\3\0\5\10\1\0"+
    "\3\10\15\0\1\10\1\103\12\10\4\0\4\10\1\0"+
    "\1\10\3\0\5\10\1\0\3\10\15\0\5\10\1\104"+
    "\4\10\1\105\1\10\4\0\4\10\1\0\1\10\3\0"+
    "\1\10\1\106\3\10\1\0\3\10\15\0\14\10\4\0"+
    "\4\10\1\0\1\10\3\0\3\10\1\107\1\10\1\0"+
    "\1\10\1\110\1\10\15\0\14\10\4\0\4\10\1\0"+
    "\1\10\3\0\3\10\1\111\1\10\1\0\3\10\15\0"+
    "\14\10\4\0\4\10\1\0\1\10\3\0\5\10\1\0"+
    "\1\10\1\112\1\10\15\0\7\10\1\113\4\10\4\0"+
    "\4\10\1\0\1\10\3\0\5\10\1\0\3\10\15\0"+
    "\1\10\1\114\12\10\4\0\4\10\1\0\1\10\3\0"+
    "\5\10\1\0\1\10\1\115\1\10\15\0\7\10\1\116"+
    "\4\10\4\0\4\10\1\0\1\10\3\0\1\10\1\117"+
    "\3\10\1\0\3\10\15\0\14\10\4\0\4\10\1\0"+
    "\1\10\3\0\3\10\1\120\1\10\1\0\3\10\15\0"+
    "\5\10\1\121\6\10\2\0\11\53\1\122\71\53\1\123"+
    "\32\53\12\55\1\0\44\55\12\0\1\124\1\125\43\0"+
    "\6\57\1\126\3\57\1\61\44\57\7\0\1\127\47\0"+
    "\1\62\1\0\5\62\1\130\47\62\1\64\1\0\55\64"+
    "\17\0\1\131\41\0\4\10\1\0\1\10\3\0\5\10"+
    "\1\0\3\10\15\0\1\10\1\132\12\10\4\0\4\10"+
    "\1\0\1\10\3\0\5\10\1\0\3\10\15\0\1\10"+
    "\1\133\12\10\4\0\4\10\1\0\1\10\3\0\5\10"+
    "\1\0\3\10\15\0\10\10\1\134\3\10\2\0\55\135"+
    "\1\136\1\135\2\0\4\10\1\0\1\10\3\0\4\10"+
    "\1\137\1\0\3\10\15\0\14\10\4\0\4\10\1\0"+
    "\1\10\3\0\5\10\1\0\3\10\15\0\1\10\1\140"+
    "\12\10\4\0\4\10\1\0\1\10\3\0\5\10\1\0"+
    "\3\10\15\0\1\141\13\10\4\0\4\10\1\0\1\10"+
    "\3\0\1\10\1\142\3\10\1\0\3\10\15\0\14\10"+
    "\4\0\4\10\1\0\1\10\3\0\5\10\1\0\3\10"+
    "\15\0\2\10\1\143\11\10\35\0\1\144\25\0\4\10"+
    "\1\0\1\10\3\0\1\10\1\145\3\10\1\0\3\10"+
    "\15\0\14\10\4\0\4\10\1\0\1\10\3\0\5\10"+
    "\1\0\3\10\15\0\10\10\1\146\3\10\4\0\4\10"+
    "\1\0\1\10\3\0\5\10\1\0\3\10\15\0\2\10"+
    "\1\147\11\10\4\0\4\10\1\0\1\10\3\0\1\10"+
    "\1\150\3\10\1\0\3\10\15\0\14\10\4\0\4\10"+
    "\1\0\1\10\3\0\5\10\1\0\3\10\15\0\11\10"+
    "\1\151\2\10\4\0\4\10\1\0\1\10\3\0\5\10"+
    "\1\0\2\10\1\152\15\0\14\10\4\0\4\10\1\0"+
    "\1\10\3\0\5\10\1\0\2\10\1\153\15\0\14\10"+
    "\4\0\4\10\1\0\1\10\3\0\5\10\1\0\3\10"+
    "\15\0\2\10\1\154\11\10\4\0\4\10\1\0\1\10"+
    "\3\0\3\10\1\155\1\10\1\0\3\10\15\0\14\10"+
    "\4\0\4\10\1\0\1\10\3\0\5\10\1\0\3\10"+
    "\15\0\1\10\1\156\12\10\4\0\4\10\1\0\1\10"+
    "\3\0\1\157\4\10\1\0\3\10\15\0\14\10\4\0"+
    "\4\10\1\0\1\10\3\0\4\10\1\160\1\0\1\161"+
    "\2\10\15\0\14\10\4\0\4\10\1\0\1\10\3\0"+
    "\5\10\1\0\3\10\15\0\2\10\1\162\11\10\4\0"+
    "\4\10\1\0\1\10\3\0\1\10\1\163\3\10\1\0"+
    "\3\10\15\0\14\10\2\0\24\53\1\0\32\53\12\0"+
    "\1\124\60\0\1\164\65\0\1\165\35\0\4\10\1\0"+
    "\1\10\3\0\1\10\1\166\3\10\1\0\3\10\15\0"+
    "\14\10\4\0\4\10\1\0\1\10\3\0\5\10\1\0"+
    "\3\10\15\0\2\10\1\167\11\10\4\0\4\10\1\0"+
    "\1\10\3\0\5\10\1\0\1\10\1\170\1\10\15\0"+
    "\14\10\2\0\1\136\1\0\53\136\1\171\1\136\2\0"+
    "\4\10\1\0\1\10\3\0\5\10\1\0\3\10\15\0"+
    "\1\10\1\172\12\10\4\0\4\10\1\0\1\10\3\0"+
    "\1\10\1\173\3\10\1\0\3\10\15\0\14\10\4\0"+
    "\4\10\1\0\1\10\3\0\5\10\1\0\3\10\15\0"+
    "\1\10\1\174\12\10\4\0\4\10\1\0\1\10\3\0"+
    "\4\10\1\175\1\0\3\10\15\0\14\10\4\0\4\10"+
    "\1\0\1\10\3\0\5\10\1\0\3\10\15\0\1\176"+
    "\13\10\4\0\4\10\1\0\1\10\3\0\4\10\1\177"+
    "\1\0\3\10\15\0\14\10\4\0\4\10\1\0\1\10"+
    "\3\0\1\10\1\200\3\10\1\0\3\10\15\0\14\10"+
    "\4\0\4\10\1\0\1\10\3\0\5\10\1\0\3\10"+
    "\15\0\3\10\1\201\10\10\4\0\4\10\1\0\1\10"+
    "\3\0\5\10\1\0\3\10\15\0\1\202\13\10\4\0"+
    "\4\10\1\0\1\10\3\0\3\10\1\203\1\10\1\0"+
    "\3\10\15\0\14\10\4\0\4\10\1\0\1\10\3\0"+
    "\5\10\1\0\3\10\15\0\7\10\1\204\4\10\4\0"+
    "\4\10\1\0\1\10\3\0\5\10\1\0\3\10\15\0"+
    "\7\10\1\205\4\10\4\0\4\10\1\0\1\10\3\0"+
    "\4\10\1\206\1\0\3\10\15\0\14\10\4\0\4\10"+
    "\1\0\1\10\3\0\5\10\1\0\3\10\15\0\2\10"+
    "\1\207\11\10\4\0\4\10\1\0\1\10\3\0\5\10"+
    "\1\0\3\10\15\0\3\10\1\210\10\10\4\0\4\10"+
    "\1\0\1\10\3\0\5\10\1\0\3\10\15\0\1\211"+
    "\13\10\4\0\4\10\1\0\1\10\3\0\5\10\1\0"+
    "\1\10\1\212\1\10\15\0\14\10\4\0\4\10\1\0"+
    "\1\10\3\0\5\10\1\0\3\10\15\0\5\10\1\213"+
    "\6\10\4\0\4\10\1\0\1\10\3\0\5\10\1\0"+
    "\3\10\15\0\11\10\1\214\2\10\17\0\1\215\61\0"+
    "\1\216\40\0\4\10\1\0\1\10\3\0\5\10\1\0"+
    "\3\10\15\0\1\217\13\10\4\0\4\10\1\0\1\10"+
    "\3\0\5\10\1\0\3\10\15\0\11\10\1\220\2\10"+
    "\2\0\1\136\1\0\7\136\1\221\43\136\1\171\1\136"+
    "\2\0\4\10\1\0\1\10\3\0\5\10\1\0\3\10"+
    "\15\0\2\10\1\222\11\10\4\0\4\10\1\0\1\10"+
    "\3\0\5\10\1\0\3\10\15\0\1\10\1\223\12\10"+
    "\4\0\4\10\1\0\1\10\3\0\5\10\1\0\2\10"+
    "\1\224\15\0\14\10\4\0\4\10\1\0\1\10\3\0"+
    "\5\10\1\0\3\10\15\0\3\10\1\225\10\10\4\0"+
    "\4\10\1\0\1\10\3\0\4\10\1\226\1\0\3\10"+
    "\15\0\14\10\4\0\4\10\1\0\1\10\3\0\5\10"+
    "\1\0\3\10\15\0\3\10\1\227\10\10\4\0\4\10"+
    "\1\0\1\10\3\0\5\10\1\0\3\10\15\0\1\230"+
    "\13\10\4\0\4\10\1\0\1\10\3\0\2\10\1\231"+
    "\2\10\1\0\3\10\15\0\14\10\4\0\4\10\1\0"+
    "\1\10\3\0\5\10\1\0\3\10\15\0\7\10\1\232"+
    "\4\10\4\0\4\10\1\0\1\10\3\0\3\10\1\233"+
    "\1\10\1\0\3\10\15\0\14\10\4\0\4\10\1\0"+
    "\1\10\3\0\5\10\1\0\3\10\15\0\6\10\1\234"+
    "\5\10\4\0\4\10\1\0\1\10\3\0\5\10\1\0"+
    "\3\10\15\0\11\10\1\235\2\10\4\0\4\10\1\0"+
    "\1\10\3\0\1\10\1\236\3\10\1\0\3\10\15\0"+
    "\14\10\20\0\1\237\61\0\1\240\37\0\4\10\1\0"+
    "\1\10\3\0\4\10\1\241\1\0\3\10\15\0\14\10"+
    "\4\0\4\10\1\0\1\10\3\0\5\10\1\0\3\10"+
    "\15\0\2\10\1\242\11\10\2\0\1\136\1\0\22\136"+
    "\1\243\30\136\1\171\1\136\2\0\4\10\1\0\1\10"+
    "\3\0\5\10\1\0\3\10\15\0\11\10\1\244\2\10"+
    "\4\0\4\10\1\0\1\10\3\0\5\10\1\0\3\10"+
    "\15\0\3\10\1\245\10\10\4\0\4\10\1\0\1\10"+
    "\3\0\2\10\1\246\2\10\1\0\3\10\15\0\14\10"+
    "\4\0\4\10\1\0\1\10\3\0\1\10\1\247\3\10"+
    "\1\0\3\10\15\0\14\10\4\0\4\10\1\0\1\10"+
    "\3\0\5\10\1\0\3\10\15\0\3\10\1\250\10\10"+
    "\4\0\4\10\1\0\1\10\3\0\5\10\1\0\3\10"+
    "\15\0\3\10\1\251\10\10\4\0\4\10\1\0\1\10"+
    "\3\0\5\10\1\0\1\252\2\10\15\0\14\10\4\0"+
    "\4\10\1\0\1\10\3\0\3\10\1\253\1\10\1\0"+
    "\3\10\15\0\14\10\4\0\4\10\1\0\1\10\3\0"+
    "\5\10\1\0\2\10\1\254\15\0\14\10\21\0\1\255"+
    "\61\0\1\256\36\0\4\10\1\0\1\10\3\0\5\10"+
    "\1\0\1\257\2\10\15\0\14\10\4\0\4\10\1\0"+
    "\1\10\3\0\5\10\1\0\3\10\15\0\7\10\1\260"+
    "\4\10\4\0\4\10\1\0\1\10\3\0\5\10\1\0"+
    "\3\10\15\0\1\261\13\10\4\0\4\10\1\0\1\10"+
    "\3\0\4\10\1\262\1\0\3\10\15\0\14\10\22\0"+
    "\1\263\61\0\1\264\35\0\4\10\1\0\1\10\3\0"+
    "\1\10\1\265\3\10\1\0\3\10\15\0\14\10\4\0"+
    "\4\10\1\0\1\10\3\0\5\10\1\0\1\266\2\10"+
    "\15\0\14\10\4\0\4\10\1\0\1\10\3\0\5\10"+
    "\1\0\3\10\15\0\2\10\1\267\11\10\4\0\4\10"+
    "\1\0\1\10\3\0\2\10\1\270\2\10\1\0\3\10"+
    "\15\0\14\10\23\0\1\271\51\0\1\272\44\0\4\10"+
    "\1\0\1\10\3\0\5\10\1\0\3\10\15\0\2\10"+
    "\1\273\11\10\4\0\4\10\1\0\1\10\3\0\1\10"+
    "\1\274\3\10\1\0\3\10\15\0\14\10\24\0\1\275"+
    "\60\0\1\276\34\0\4\10\1\0\1\10\3\0\5\10"+
    "\1\0\1\10\1\277\1\10\15\0\14\10\25\0\1\300"+
    "\35\0\4\10\1\0\1\10\3\0\5\10\1\0\3\10"+
    "\15\0\11\10\1\301\2\10\16\0\1\302\66\0\1\123"+
    "\32\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6815];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\1\1\11\17\1\7\11\1\1\4\11\12\1"+
    "\1\11\1\1\1\0\2\1\1\0\1\11\3\0\1\1"+
    "\1\0\4\1\1\0\7\1\1\0\17\1\1\0\1\11"+
    "\1\1\1\0\1\1\1\11\1\1\1\0\3\1\1\11"+
    "\1\0\5\1\1\11\17\1\2\0\3\1\1\0\23\1"+
    "\2\0\2\1\1\0\15\1\2\0\14\1\2\0\4\1"+
    "\2\0\4\1\2\0\2\1\1\0\1\11\1\1\1\0"+
    "\1\1\1\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[194];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */



  _HaskellLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  _HaskellLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 148) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
      return;

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 57: 
          { return HaskellTokenTypes.CONSTRUCTOR_KEYWORD;
          }
        case 58: break;
        case 44: 
          { return HaskellTokenTypes.USING_KEYWORD;
          }
        case 59: break;
        case 33: 
          { return HaskellTokenTypes.THREE_DOTS;
          }
        case 60: break;
        case 9: 
          { return HaskellTokenTypes.LEFT_BRACE;
          }
        case 61: break;
        case 54: 
          { return HaskellTokenTypes.RENAMING_KEYWORD;
          }
        case 62: break;
        case 14: 
          { return HaskellTokenTypes.RIGHT_PAREN;
          }
        case 63: break;
        case 17: 
          { return HaskellTokenTypes.DOT;
          }
        case 64: break;
        case 1: 
          { return HaskellTokenTypes.COMMENT;
          }
        case 65: break;
        case 23: 
          { return HaskellTokenTypes.STRING;
          }
        case 66: break;
        case 6: 
          { return HaskellTokenTypes.ID;
          }
        case 67: break;
        case 56: 
          { yybegin(TEX); return HaskellTokenTypes.COMMENT;
          }
        case 68: break;
        case 7: 
          { return TokenType.WHITE_SPACE;
          }
        case 69: break;
        case 27: 
          { return HaskellTokenTypes.OF_KEYWORD;
          }
        case 70: break;
        case 11: 
          { return HaskellTokenTypes.LEFT_BRACKET;
          }
        case 71: break;
        case 21: 
          { return HaskellTokenTypes.ARROW;
          }
        case 72: break;
        case 25: 
          { return HaskellTokenTypes.IN_KEYWORD;
          }
        case 73: break;
        case 10: 
          { return HaskellTokenTypes.RIGHT_BRACE;
          }
        case 74: break;
        case 42: 
          { return HaskellTokenTypes.CLASS_KEYWORD;
          }
        case 75: break;
        case 28: 
          { return HaskellTokenTypes.DO_KEYWORD;
          }
        case 76: break;
        case 36: 
          { return HaskellTokenTypes.CASE_KEYWORD;
          }
        case 77: break;
        case 5: 
          { return HaskellTokenTypes.TYPE_CONS;
          }
        case 78: break;
        case 3: 
          { return TokenType.NEW_LINE_INDENT;
          }
        case 79: break;
        case 43: 
          { return HaskellTokenTypes.FIELD_KEYWORD;
          }
        case 80: break;
        case 31: 
          { return HaskellTokenTypes.CHARACTER;
          }
        case 81: break;
        case 49: 
          { return HaskellTokenTypes.MODULE_KEYWORD;
          }
        case 82: break;
        case 46: 
          { return HaskellTokenTypes.IMPORT_KEYWORD;
          }
        case 83: break;
        case 18: 
          { return HaskellTokenTypes.COMMA;
          }
        case 84: break;
        case 53: 
          { return HaskellTokenTypes.INSTANCE_KEYWORD;
          }
        case 85: break;
        case 4: 
          { return HaskellTokenTypes.NUMBER;
          }
        case 86: break;
        case 37: 
          { return HaskellTokenTypes.OPEN_KEYWORD;
          }
        case 87: break;
        case 15: 
          { return HaskellTokenTypes.COLON;
          }
        case 88: break;
        case 2: 
          { return TokenType.BAD_CHARACTER;
          }
        case 89: break;
        case 38: 
          { return HaskellTokenTypes.DATA_KEYWORD;
          }
        case 90: break;
        case 20: 
          { return HaskellTokenTypes.VERTICAL_BAR;
          }
        case 91: break;
        case 26: 
          { return HaskellTokenTypes.IF_KEYWORD;
          }
        case 92: break;
        case 35: 
          { return HaskellTokenTypes.ELSE_KEYWORD;
          }
        case 93: break;
        case 51: 
          { return HaskellTokenTypes.PUBLIC_KEYWORD;
          }
        case 94: break;
        case 50: 
          { return HaskellTokenTypes.MUTUAL_KEYWORD;
          }
        case 95: break;
        case 13: 
          { return HaskellTokenTypes.LEFT_PAREN;
          }
        case 96: break;
        case 52: 
          { return HaskellTokenTypes.RECORD_KEYWORD;
          }
        case 97: break;
        case 41: 
          { return HaskellTokenTypes.WITH_KEYWORD;
          }
        case 98: break;
        case 24: 
          { return HaskellTokenTypes.END_OF_LINE_COMMENT;
          }
        case 99: break;
        case 30: 
          { yybegin(YYINITIAL); return HaskellTokenTypes.COMMENT;
          }
        case 100: break;
        case 19: 
          { return HaskellTokenTypes.ASSIGNMENT;
          }
        case 101: break;
        case 39: 
          { return HaskellTokenTypes.THEN_KEYWORD;
          }
        case 102: break;
        case 22: 
          { return HaskellTokenTypes.FORALL;
          }
        case 103: break;
        case 48: 
          { return HaskellTokenTypes.HIDING_KEYWORD;
          }
        case 104: break;
        case 29: 
          { return HaskellTokenTypes.AS_KEYWORD;
          }
        case 105: break;
        case 12: 
          { return HaskellTokenTypes.RIGHT_BRACKET;
          }
        case 106: break;
        case 55: 
          { return HaskellTokenTypes.POSTULATE_KEYWORD;
          }
        case 107: break;
        case 40: 
          { return HaskellTokenTypes.TYPE_KEYWORD;
          }
        case 108: break;
        case 8: 
          { return HaskellTokenTypes.LAMBDA;
          }
        case 109: break;
        case 32: 
          { yybegin(BLOCK_COMMENT); return HaskellTokenTypes.COMMENT;
          }
        case 110: break;
        case 45: 
          { return HaskellTokenTypes.WHERE_KEYWORD;
          }
        case 111: break;
        case 34: 
          { return HaskellTokenTypes.LET_KEYWORD;
          }
        case 112: break;
        case 47: 
          { return HaskellTokenTypes.PRAGMA;
          }
        case 113: break;
        case 16: 
          { return HaskellTokenTypes.SEMICOLON;
          }
        case 114: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
