/* The following code was generated by JFlex 1.5.1 */

package org.jetbrains.yesod.hamlet.parser;

/**
 * @author Leyla H
 */

import java.util.*;
import com.intellij.lexer.*;
import com.intellij.psi.*;
import org.jetbrains.haskell.parser.token.*;
import com.intellij.psi.tree.IElementType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.1
 * from the specification file <tt>/Users/atsky/work/haskell-idea-plugin/plugin/src/org/jetbrains/yesod/hamlet/parser/Hamlet.flex</tt>
 */
class _HamletLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\4\1\47\1\2\1\47\22\0\1\2\1\15\1\0"+
    "\1\17\1\5\5\0\1\27\2\0\1\3\1\20\1\0\12\1\2\0"+
    "\1\16\1\25\1\26\1\22\1\21\32\1\1\0\1\46\1\0\1\31"+
    "\1\30\1\0\1\37\1\41\1\10\1\6\1\14\1\33\1\44\1\43"+
    "\1\32\2\1\1\34\1\40\1\42\1\7\1\13\1\1\1\36\1\35"+
    "\1\11\2\1\1\45\1\1\1\12\1\1\1\23\1\0\1\24\7\0"+
    "\1\47\u1fa2\0\1\47\1\47\udfd6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\2\1\4\1\5\1\1"+
    "\1\6\1\1\1\7\1\1\1\10\1\11\1\12\1\1"+
    "\1\2\1\1\1\13\1\2\4\0\1\14\6\0\1\15"+
    "\1\16\1\17\1\0\1\20\1\21\1\22\1\23\1\24"+
    "\1\0\1\25\2\0\1\26\4\0\1\16\1\0\1\27"+
    "\7\0\1\30\1\0\1\31\1\32\3\0\1\33\3\0"+
    "\1\34\2\0\1\35\1\36\1\0\1\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[77];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\50\0\310\0\360"+
    "\0\u0118\0\u0140\0\50\0\u0168\0\50\0\50\0\50\0\u0190"+
    "\0\u01b8\0\u01e0\0\50\0\u0208\0\u0230\0\u0258\0\u0280\0\u02a8"+
    "\0\50\0\u02d0\0\u02f8\0\u0320\0\u0348\0\u0370\0\u0398\0\50"+
    "\0\u03c0\0\50\0\u03e8\0\50\0\50\0\50\0\50\0\50"+
    "\0\u0410\0\50\0\u0438\0\u0460\0\50\0\u0488\0\u04b0\0\u04d8"+
    "\0\u0500\0\50\0\u0528\0\50\0\u0550\0\u0578\0\u05a0\0\u05c8"+
    "\0\u05f0\0\u0618\0\u0640\0\u0668\0\u0690\0\50\0\u06b8\0\u06e0"+
    "\0\u0708\0\u0730\0\50\0\u0758\0\u0780\0\u07a8\0\50\0\u07d0"+
    "\0\u07f8\0\50\0\50\0\u0820\0\50";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[77];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\7\3\1\10"+
    "\1\11\1\12\1\13\1\14\2\2\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\14\3\1\23\52\0\1\3\1\0"+
    "\1\3\2\0\7\3\13\0\1\3\1\0\14\3\4\0"+
    "\1\4\46\0\1\3\1\0\1\24\2\0\7\3\13\0"+
    "\1\3\1\0\14\3\10\0\1\25\1\26\1\27\3\0"+
    "\1\30\2\0\1\31\12\0\1\32\1\33\4\0\1\34"+
    "\1\0\1\35\2\0\1\36\17\0\1\37\35\0\1\40"+
    "\11\0\1\41\55\0\1\42\46\0\1\43\1\44\47\0"+
    "\1\45\25\0\1\3\1\0\1\3\2\0\7\3\6\0"+
    "\1\46\4\0\1\3\1\0\14\3\25\0\1\47\25\0"+
    "\1\3\1\0\1\3\2\0\7\3\11\0\1\50\1\0"+
    "\1\3\1\0\14\3\11\0\1\51\73\0\1\52\53\0"+
    "\1\53\44\0\1\54\46\0\1\55\23\0\1\56\77\0"+
    "\1\57\17\0\1\60\72\0\1\61\32\0\1\62\35\0"+
    "\1\63\67\0\1\64\34\0\1\65\74\0\1\66\47\0"+
    "\1\67\50\0\1\70\23\0\1\71\46\0\1\72\47\0"+
    "\1\73\41\0\1\74\55\0\1\75\52\0\1\76\47\0"+
    "\1\77\72\0\1\100\51\0\1\101\51\0\1\102\47\0"+
    "\1\103\23\0\1\31\42\0\1\104\67\0\1\105\51\0"+
    "\1\106\27\0\1\107\65\0\1\110\30\0\1\111\67\0"+
    "\1\112\50\0\1\113\55\0\1\114\21\0\1\62\77\0"+
    "\1\115\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2120];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\4\1\1\11\1\1\3\11"+
    "\3\1\1\11\1\1\4\0\1\11\6\0\1\11\1\1"+
    "\1\11\1\0\5\11\1\0\1\11\2\0\1\11\4\0"+
    "\1\11\1\0\1\11\7\0\1\1\1\0\1\11\1\1"+
    "\3\0\1\11\3\0\1\11\2\0\2\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[77];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char[] zzBuffer = new char[0];

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  _HamletLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  _HamletLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 130) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer.toString().toCharArray();
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { return TokenType.BAD_CHARACTER;
          }
        case 32: break;
        case 2: 
          { return HamletTokenTypes.IDENTIFIER;
          }
        case 33: break;
        case 3: 
          { return TokenType.WHITE_SPACE;
          }
        case 34: break;
        case 4: 
          { return HamletTokenTypes.NEWLINE;
          }
        case 35: break;
        case 5: 
          { return HamletTokenTypes.DOLLAR;
          }
        case 36: break;
        case 6: 
          { return HamletTokenTypes.OANGLE;
          }
        case 37: break;
        case 7: 
          { return HamletTokenTypes.DOT;
          }
        case 38: break;
        case 8: 
          { return HamletTokenTypes.CCURLY;
          }
        case 39: break;
        case 9: 
          { return HamletTokenTypes.EQUAL;
          }
        case 40: break;
        case 10: 
          { return HamletTokenTypes.CANGLE;
          }
        case 41: break;
        case 11: 
          { return HamletTokenTypes.BACKSLASH;
          }
        case 42: break;
        case 12: 
          { return HamletTokenTypes.COMMENTS;
          }
        case 43: break;
        case 13: 
          { return HamletTokenTypes.BINDSTATMENT;
          }
        case 44: break;
        case 14: 
          { return HamletTokenTypes.DOCTYPE_ALL;
          }
        case 45: break;
        case 15: 
          { return HamletTokenTypes.SHARP;
          }
        case 46: break;
        case 16: 
          { return HamletTokenTypes.AT;
          }
        case 47: break;
        case 17: 
          { return HamletTokenTypes.STAR;
          }
        case 48: break;
        case 18: 
          { return HamletTokenTypes.UNDERSCORE;
          }
        case 49: break;
        case 19: 
          { return HamletTokenTypes.HAT;
          }
        case 50: break;
        case 20: 
          { return HamletTokenTypes.COMMENT_END;
          }
        case 51: break;
        case 21: 
          { return HamletTokenTypes.OF_DOLLAR;
          }
        case 52: break;
        case 22: 
          { return HamletTokenTypes.IF_DOLLAR;
          }
        case 53: break;
        case 23: 
          { return HamletTokenTypes.OCURLY;
          }
        case 54: break;
        case 24: 
          { return HamletTokenTypes.COMMENT_START;
          }
        case 55: break;
        case 25: 
          { return HamletTokenTypes.CASE_DOLLAR;
          }
        case 56: break;
        case 26: 
          { return HamletTokenTypes.ELSE_DOLLAR;
          }
        case 57: break;
        case 27: 
          { return HamletTokenTypes.WITH_DOLLAR;
          }
        case 58: break;
        case 28: 
          { return HamletTokenTypes.MAYBE_DOLLAR;
          }
        case 59: break;
        case 29: 
          { return HamletTokenTypes.ELSEIF_DOLLAR;
          }
        case 60: break;
        case 30: 
          { return HamletTokenTypes.FORALL_DOLLAR;
          }
        case 61: break;
        case 31: 
          { return HamletTokenTypes.NOTHING_DOLLAR;
          }
        case 62: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
