package org.jetbrains.cabal.parser

import com.intellij.psi.tree.IElementType

public val FIELD_TYPES: Map<String, IElementType> = mapOf(
         "version"              to CabalTokelTypes.VERSION           ,
         "cabal-version"        to CabalTokelTypes.CABAL_VERSION     ,
         "name"                 to CabalTokelTypes.NAME_FIELD        ,
         "build-type"           to CabalTokelTypes.BUILD_TYPE_FIELD  ,
         "license"              to CabalTokelTypes.LICENSE           ,
         "tested-with"          to CabalTokelTypes.TESTED_WITH       ,
         "license-file"         to CabalTokelTypes.LICENSE_FILES     ,
         "license-files"        to CabalTokelTypes.LICENSE_FILES     ,
         "data-dir"             to CabalTokelTypes.DIRECTORY_FIELD   ,
         "maintainer"           to CabalTokelTypes.MAINTAINER        ,
         "main-is"              to CabalTokelTypes.MAIN_FILE         ,
         "build-depends"        to CabalTokelTypes.BUILD_DEPENDS     ,
         "pkgconfig-depends"    to CabalTokelTypes.PKG_CONFIG_DEPENDS,
         "build-tools"          to CabalTokelTypes.BUILD_TOOLS       ,
         "buildable"            to CabalTokelTypes.BUILDABLE         ,
         "extensions"           to CabalTokelTypes.EXTENSIONS        ,
         "other-modules"        to CabalTokelTypes.OTHER_MODULES     ,
         "exposed-modules"      to CabalTokelTypes.EXPOSED_MODULES   ,
         "exposed"              to CabalTokelTypes.EXPOSED           ,
         "package-url"          to CabalTokelTypes.URL_FIELD         ,
         "homepage"             to CabalTokelTypes.URL_FIELD         ,
         "bug-reports"          to CabalTokelTypes.URL_FIELD         ,
         "location"             to CabalTokelTypes.URL_FIELD         ,
         "extra-doc-files"      to CabalTokelTypes.FILE_LIST         ,
         "extra-tmp-files"      to CabalTokelTypes.FILE_LIST         ,
         "data-files"           to CabalTokelTypes.FILE_LIST         ,
         "extra-source-files"   to CabalTokelTypes.FILE_LIST         ,
         "includes"             to CabalTokelTypes.FILE_LIST         ,
         "install-includes"     to CabalTokelTypes.FILE_LIST         ,
         "c-sources"            to CabalTokelTypes.FILE_LIST         ,
         "copyright"            to CabalTokelTypes.FREE_FIELD        ,
         "author"               to CabalTokelTypes.FREE_FIELD        ,
         "stability"            to CabalTokelTypes.FREE_FIELD        ,
         "synopsis"             to CabalTokelTypes.FREE_FIELD        ,
         "description"          to CabalTokelTypes.FREE_FIELD        ,
         "category"             to CabalTokelTypes.FREE_FIELD        ,
         "ghc-options"          to CabalTokelTypes.OPTIONS_FIELD     ,
         "ghc-prof-options"     to CabalTokelTypes.OPTIONS_FIELD     ,
         "ghc-shared-options"   to CabalTokelTypes.OPTIONS_FIELD     ,
         "hugs-options"         to CabalTokelTypes.OPTIONS_FIELD     ,
         "nhc98-options"        to CabalTokelTypes.OPTIONS_FIELD     ,
         "cc-options"           to CabalTokelTypes.OPTIONS_FIELD     ,
         "cpp-options"          to CabalTokelTypes.OPTIONS_FIELD     ,
         "ld-options"           to CabalTokelTypes.OPTIONS_FIELD     ,
         "type"                 to CabalTokelTypes.TOKEN_FIELD       ,
         "module"               to CabalTokelTypes.REPO_MODULE       ,
         "branch"               to CabalTokelTypes.TOKEN_FIELD       ,
         "tag"                  to CabalTokelTypes.TOKEN_FIELD       ,
         "test-module"          to CabalTokelTypes.TEST_MODULE       ,
         "frameworks"           to CabalTokelTypes.TOKEN_LIST        ,
         "extra-libraries"      to CabalTokelTypes.TOKEN_LIST        ,
         "subdir"               to CabalTokelTypes.DIRECTORY_FIELD   ,
         "hs-source-dirs"       to CabalTokelTypes.DIRECTORY_LIST    ,
         "extra-lib-dirs"       to CabalTokelTypes.DIRECTORY_LIST    ,
         "include-dirs"         to CabalTokelTypes.DIRECTORY_LIST    ,
         "default"              to CabalTokelTypes.BOOL_FIELD        ,
         "manual"               to CabalTokelTypes.BOOL_FIELD
)
